/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BaseBotService } from "../baseBot.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BaseBotCreateInput } from "./BaseBotCreateInput";
import { BaseBot } from "./BaseBot";
import { BaseBotFindManyArgs } from "./BaseBotFindManyArgs";
import { BaseBotWhereUniqueInput } from "./BaseBotWhereUniqueInput";
import { BaseBotUpdateInput } from "./BaseBotUpdateInput";
import { BotFindManyArgs } from "../../bot/base/BotFindManyArgs";
import { Bot } from "../../bot/base/Bot";
import { BotWhereUniqueInput } from "../../bot/base/BotWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BaseBotControllerBase {
  constructor(
    protected readonly service: BaseBotService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BaseBot })
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createBaseBot(
    @common.Body() data: BaseBotCreateInput
  ): Promise<BaseBot> {
    return await this.service.createBaseBot({
      data: {
        ...data,

        aiModel: data.aiModel
          ? {
              connect: data.aiModel,
            }
          : undefined,
      },
      select: {
        aiModel: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BaseBot] })
  @ApiNestedQuery(BaseBotFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async baseBots(@common.Req() request: Request): Promise<BaseBot[]> {
    const args = plainToClass(BaseBotFindManyArgs, request.query);
    return this.service.baseBots({
      ...args,
      select: {
        aiModel: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BaseBot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async baseBot(
    @common.Param() params: BaseBotWhereUniqueInput
  ): Promise<BaseBot | null> {
    const result = await this.service.baseBot({
      where: params,
      select: {
        aiModel: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BaseBot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateBaseBot(
    @common.Param() params: BaseBotWhereUniqueInput,
    @common.Body() data: BaseBotUpdateInput
  ): Promise<BaseBot | null> {
    try {
      return await this.service.updateBaseBot({
        where: params,
        data: {
          ...data,

          aiModel: data.aiModel
            ? {
                connect: data.aiModel,
              }
            : undefined,
        },
        select: {
          aiModel: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BaseBot })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteBaseBot(
    @common.Param() params: BaseBotWhereUniqueInput
  ): Promise<BaseBot | null> {
    try {
      return await this.service.deleteBaseBot({
        where: params,
        select: {
          aiModel: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/bots")
  @ApiNestedQuery(BotFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Bot",
    action: "read",
    possession: "any",
  })
  async findBots(
    @common.Req() request: Request,
    @common.Param() params: BaseBotWhereUniqueInput
  ): Promise<Bot[]> {
    const query = plainToClass(BotFindManyArgs, request.query);
    const results = await this.service.findBots(params.id, {
      ...query,
      select: {
        baseBot: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,
        name: true,
        tokensRequired: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bots")
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "update",
    possession: "any",
  })
  async connectBots(
    @common.Param() params: BaseBotWhereUniqueInput,
    @common.Body() body: BotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bots: {
        connect: body,
      },
    };
    await this.service.updateBaseBot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bots")
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "update",
    possession: "any",
  })
  async updateBots(
    @common.Param() params: BaseBotWhereUniqueInput,
    @common.Body() body: BotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bots: {
        set: body,
      },
    };
    await this.service.updateBaseBot({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bots")
  @nestAccessControl.UseRoles({
    resource: "BaseBot",
    action: "update",
    possession: "any",
  })
  async disconnectBots(
    @common.Param() params: BaseBotWhereUniqueInput,
    @common.Body() body: BotWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bots: {
        disconnect: body,
      },
    };
    await this.service.updateBaseBot({
      where: params,
      data,
      select: { id: true },
    });
  }
}
